INSERT INTO ORM_DISCIPLINE VALUES(1,'Biology');
INSERT INTO ORM_DISCIPLINE VALUES(2,'Physics');
INSERT INTO ORM_DISCIPLINE VALUES(3,'Math');

INSERT INTO ORM_TEST VALUES(1,'T1');
INSERT INTO ORM_TEST VALUES(2,'T2');
INSERT INTO ORM_TEST VALUES(3,'T3');

INSERT INTO ORM_USER VALUES(1, 'poll@gmail.com', 'feghhh2', 'ADMIN', 'Poll', 'Wessley');
INSERT INTO ORM_USER VALUES(2, 'kate@gmail.com', 'kdddwh66', 'STANDART', 'Kate', 'Winslet');
INSERT INTO ORM_USER VALUES(3, 'tom@gmail.com', 'jhh8hjjn', 'STANDART', 'Tom', 'Holland');

INSERT INTO ORM_QUESTION VALUES(1,'qtext1',3, 1);
INSERT INTO ORM_QUESTION VALUES(2,'qtext2',1, 2);
INSERT INTO ORM_QUESTION VALUES(3,'qtext3',1, 2);

INSERT INTO ORM_ANSWER_VARIANT VALUES(1,'atext1','false',1);
INSERT INTO ORM_ANSWER_VARIANT VALUES(2,'atext2','true',2);
INSERT INTO ORM_ANSWER_VARIANT VALUES(3,'atext3','false',3);




















