# Generated by Django 3.0.1 on 2019-12-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0003_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
