# Generated by Django 3.0.1 on 2019-12-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0006_auto_20191224_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher_lectures',
            field=models.ManyToManyField(to='vcs.Lecture'),
        ),
    ]
