# Generated by Django 3.0.1 on 2019-12-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0007_user_teacher_lectures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('version', 'name')},
        ),
    ]
