# Generated by Django 3.0.1 on 2019-12-24 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0008_auto_20191224_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcs.LecturePack'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='prev_lecture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vcs.Lecture'),
        ),
    ]
