# Generated by Django 3.0.1 on 2019-12-24 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0010_auto_20191224_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='last',
            field=models.BooleanField(default=True),
        ),
    ]
