# Generated by Django 3.0.1 on 2019-12-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0011_lecture_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='last',
        ),
    ]
