# Generated by Django 3.0.1 on 2019-12-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0012_remove_lecture_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureactivity',
            name='comment_count',
        ),
        migrations.AddField(
            model_name='lecture',
            name='original_lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vcs.Lecture'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('version', 'original_lecture')},
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='prev_lecture',
        ),
    ]
