# Generated by Django 3.0.1 on 2019-12-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0013_auto_20191224_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='original_lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vcs.Lecture'),
        ),
    ]
