# Generated by Django 3.0.1 on 2019-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0015_auto_20191224_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectureactivity',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lectureactivity',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lectureactivity',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
