# Generated by Django 3.0.1 on 2019-12-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcs', '0016_auto_20191224_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureactivity',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='lecturecomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='lectureactivity',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturecomment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecturecomment',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
